from snakemake.utils import min_version

# ------------- min snakemake version ------------

min_version("6.7.0")


# ------------- setup ------------


configfile: "config/config.yaml"


report: "report/workflow.rst"


# ------------- load rules ------------


include: "rules/common.smk"
include: "rules/indelrealign.smk"
include: "rules/callvariants.smk"


# ------------- workflow ------------


rule all:
    input:
        get_variant_call_output(),
